steps:
  # Step 1: Install Packer
  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip', '-O', '/workspace/packer.zip']
  - name: 'gcr.io/cloud-builders/unzip'
    args: ['-o', '/workspace/packer.zip', '-d', '/workspace']
  - name: 'gcr.io/cloud-builders/wget'
    args: ['https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_SHA256SUMS', '-O', '/workspace/packer_SHA256SUMS']
  - name: 'busybox'
    entrypoint: 'sha256sum'
    args: ['-c', '/workspace/packer']

  # Step 2: Validate the Packer template
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/workspace/packer'
    args: ['validate', './wordpress.json']

  # Step 3: Build the image using Packer
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/workspace/packer'
    args: ['build', './wordpress.json']


options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s
