steps:
# Install Packer
- name: 'gcr.io/cloud-builders/wget'
  args: ['https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip', '-O', '/tmp/packer.zip']
- name: 'gcr.io/cloud-builders/unzip'
  args: ['/tmp/packer.zip', '-d', '/tmp']
- name: 'gcr.io/cloud-builders/wget'
  args: ['https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_SHA256SUMS', '-O', '/tmp/packer_SHA256SUMS']
- name: 'gcr.io/cloud-builders/sha256sum'
  args: ['-c', '--ignore-missing', '/tmp/packer_SHA256SUMS']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '/tmp/packer', '/workspace']

# Install Ansible
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--rm', '-v', '/workspace:/workspace', 'python:3.8', '/bin/sh', '-c', 'pip install ansible && cp -r /usr/local/lib/python3.8/site-packages /workspace/ansible']

# Run Packer with Ansible provisioner
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/workspace/packer'
  args: ['build', '-var', 'ansible_playbook_path=/workspace/ansible/main-playbook.yml', '-var', 'ansible_roles_path=/workspace/roles', 'wordpress.json']
