steps:
# Use Cloud Shell image to Install Packer
- name: 'gcr.io/cloudshell-images/cloudshell:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update && apt-get install -y wget unzip
    wget https://releases.hashicorp.com/packer/1.7.8/packer_1.7.8_linux_amd64.zip -O /workspace/packer.zip
    unzip -o /workspace/packer.zip -d /workspace

# Install Ansible
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'run'
  - '--rm'
  - '-v'
  - '/workspace:/workspace'
  - 'python:3.8'
  - '/bin/sh'
  - '-c'
  - 'pip install ansible && cp -r /usr/local/lib/python3.8/site-packages /workspace/ansible'

# Run Packer with Ansible provisioner
- name: 'gcr.io/cloudshell-images/cloudshell:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    export NEW_PATH=$_PATH:/workspace/ansible/bin 
    $_NEW_PATH/. build -var "ansible_playbook_path=/workspace/main-playbook.yml" -var "ansible_roles_path=/workspace/roles" wordpress.json

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1600s
