steps:
- name: 'hashicorp/packer:1.7.6'
  entrypoint: 'bash'
  args: ['-c', 'yum install ansible']

- name: 'hashicorp/packer:1.7.6'
  entrypoint: packer
  args: ['build', '-var', 'project_id=$PROJECT_ID', 'wordpress.json']
  env:
  - 'PACKER_LOG=1'
  - 'PACKER_LOG_PATH=packer.log'
  timeout: 2600s
  
options:
  logging : CLOUD_LOGGING_ONLY
timeout: 2600s

